const EVENTS_CONSTANT = {
  DEPOSIT: 'deposit',
  VIEW_SEND: 'view_send',
  SEND: 'send',
  SEND_SUCCESS: 'send_success',
  SEND_FAILED: 'send_failed',
  VIEW_WITHDRAW: 'view_withdraw',
  WITHDRAW: 'withdraw',
  WITHDRAW_SUCCESS: 'withdraw_success',
  WITHDRAW_FAILED: 'withdraw_failed',
  DEPOSIT_PDEX: 'deposit_pdex',
  DEPOSIT_PDEX_SUCCESS: 'deposit_pdex_success',
  DEPOSIT_PDEX_FAILED: 'deposit_pdex_failed',
  TRADE: 'trade',
  TRADE_SUCCESS: 'trade_success',
  TRADE_FAILED: 'trade_failed',
  WITHDRAW_PDEX: 'withdraw_pdex',
  WITHDRAW_PDEX_SUCCESS: 'withdraw_pdex_success',
  WITHDRAW_PDEX_FAILED: 'withdraw_pdex_failed',
  CLICK_HOME_BUY: 'click_home_buy',
  CLICK_HOME_TRADE: 'click_home_trade',
  CLICK_HOME_UNISWAP: 'click_home_uniswap',
  DEPOSIT_UNISWAP: 'deposit_uniswap',
  DEPOSIT_UNISWAP_SUCCESS: 'deposit_uniswap_success',
  DEPOSIT_UNISWAP_FAILED: 'deposit_uniswap_failed',
  TRADE_UNISWAP: 'trade_uniswap',
  TRADE_UNISWAP_SUCCESS: 'trade_uniswap_success',
  TRADE_UNISWAP_FAILED: 'trade_uniswap_failed',
  WITHDRAW_UNISWAP: 'withdraw_uniswap',
  WITHDRAW_UNISWAP_SUCCESS: 'withdraw_uniswap_success',
  WITHDRAW_UNISWAP_FAILED: 'withdraw_uniswap_failed',
  WITHDRAW_UNISWAP_SC: 'withdraw_uniswap_sc',
  WITHDRAW_UNISWAP_SC_SUCCESS: 'withdraw_uniswap_sc_success',
  WITHDRAW_UNISWAP_SC_FAILED: 'withdraw_uniswap_sc_failed',
  NOTIFICATION: 'notification',
  CLICK_NOTIFICATION: 'click_notification',
};

export default EVENTS_CONSTANT;
