const prefixNetwork = 'testnet';

const isMainnet = false;

interface IKeys {
    PASSPHRASE_KEY: string;
    DEFAULT_ACCOUNT_NAME: string;
    DISPLAYED_WIZARD: string;
    GAME_PLAYER_ID: string;
    USER: string;
    LIST_DEVICE: string;
    LIST_TOKEN: string;
    USER_UNFOLLOWING_TOKEN_ID_LIST: string;
    DEX: string;
    DEX_HISTORY: string;
    UNISWAP_HISTORY: string;
    SEEN_DEPOSIT_GUIDE: string;
    PIN: string;
    IS_CHECK_FOLLOWED_TOKEN: string;
    IS_BACKEDUP_ACCOUNT: string;
    REDUX_STATE_RECEIVERS_IN_NETWORK: string;
    REDUX_STATE_RECEIVERS_OUT_NETWORK: string;
    WITHDRAWAL_DATA: string;
    SUBSCRIBE_TOPIC_KEY: string;
    BACKUP_STAKE_KEY: string;
    SCREEN_STAKE_GUIDE: string;
    WEBVIEW: string;
    PROVIDE_TXS: string;
    SHOW_WIZARD: string;
    IS_FOLLOW_DEFAULT_PTOKENS: string;
    DETECT_NETWORK_NAME: string;
    DEV_TEST_MODE_CENTRALIZED: string;
    DEV_TEST_MODE_DECENTRALIZED: string;
    UNSHIELD_DATA_DECENTRALIZED: string;
    UNSHIELD_DATA_CENTRALIZED: string;
    DEV_TEST_TOGGLE_UTXOS: string;
    UTXOS_DATA: string;
    DEV_TEST_TOGGLE_HISTORY_DETAIL: string;
    DEV_TEST_TOGGLE_LOG_APP: string;
}

interface IKeysTestnet {
    PASSPHRASE_KEY: string;
    DEFAULT_ACCOUNT_NAME: string;
    DISPLAYED_WIZARD: string;
    GAME_PLAYER_ID: string;
    USER: string;
    LIST_DEVICE: string;
    LIST_TOKEN: string;
    USER_UNFOLLOWING_TOKEN_ID_LIST: string;
    DEX: string;
    UNISWAP_HISTORY: string;
    DEX_HISTORY: string;
    SEEN_DEPOSIT_GUIDE: string;
    PIN: string;
    IS_CHECK_FOLLOWED_TOKEN: string;
    IS_BACKEDUP_ACCOUNT: string;
    REDUX_STATE_RECEIVERS_IN_NETWORK: string;
    REDUX_STATE_RECEIVERS_OUT_NETWORK: string;
    WITHDRAWAL_DATA: string;
    SUBSCRIBE_TOPIC_KEY: string;
    BACKUP_STAKE_KEY: string;
    SCREEN_STAKE_GUIDE: string;
    PROVIDE_TXS: string;
    SHOW_WIZARD: string;
    IS_FOLLOW_DEFAULT_PTOKENS: string;
    DETECT_NETWORK_NAME: string;
    DEV_TEST_MODE_CENTRALIZED: string;
    DEV_TEST_MODE_DECENTRALIZED: string;
    UNSHIELD_DATA_DECENTRALIZED: string;
    UNSHIELD_DATA_CENTRALIZED: string;
    DEV_TEST_TOGGLE_UTXOS: string;
    UTXOS_DATA: string;
    DEV_TEST_TOGGLE_HISTORY_DETAIL: string;
    DEV_TEST_TOGGLE_LOG_APP: string;
}

const KEYS: IKeys = {
    PASSPHRASE_KEY: '$password',
    DEFAULT_ACCOUNT_NAME: '$DEFAULT_ACCOUNT_NAME',
    DISPLAYED_WIZARD: '$DISPLAYED_WIZARD',
    GAME_PLAYER_ID: '$GAME_PLAYER_ID',
    USER: 'USER_OBJECT_KEY',
    LIST_DEVICE: 'PRODUCT_LIST_KEY',
    LIST_TOKEN: 'LIST_TOKEN',
    USER_UNFOLLOWING_TOKEN_ID_LIST: '$USER_UNFOLLOWING_TOKEN_ID_LIST',
    DEX: '$DEX',
    DEX_HISTORY: '$DEX_HISTORY',
    UNISWAP_HISTORY: '$UNISWAP_HISTORY',
    SEEN_DEPOSIT_GUIDE: '$SEEN_DEPOSIT_GUIDE',
    PIN: '$PIN',
    IS_CHECK_FOLLOWED_TOKEN: '$IS_CHECK_FOLLOWED_TOKEN',
    IS_BACKEDUP_ACCOUNT: '$IS_BACKEDUP_ACCOUNT',
    REDUX_STATE_RECEIVERS_IN_NETWORK: '$REDUX_STATE_RECEIVERS_IN_NETWORK',
    REDUX_STATE_RECEIVERS_OUT_NETWORK: '$REDUX_STATE_RECEIVERS_OUT_NETWORK',
    WITHDRAWAL_DATA: '$WITHDRAWAL_DATA',
    SUBSCRIBE_TOPIC_KEY: 'all-production',
    BACKUP_STAKE_KEY: '$BACKUP_STAKE_KEY',
    SCREEN_STAKE_GUIDE: '$SCREEN_STAKE_GUIDE',
    WEBVIEW: '$WEBVIEW',
    PROVIDE_TXS: '$PROVIDE_TXS',
    SHOW_WIZARD: '$SHOW_WIZARD',
    IS_FOLLOW_DEFAULT_PTOKENS: '$IS_FOLLOW_DEFAULT_PTOKENS',
    DETECT_NETWORK_NAME: '$DETECT_NETWORK_NAME',
    DEV_TEST_MODE_CENTRALIZED: '$DEV_TEST_MODE_CENTRALIZED',
    DEV_TEST_MODE_DECENTRALIZED: '$DEV_TEST_MODE_DECENTRALIZED',
    UNSHIELD_DATA_DECENTRALIZED: '$UNSHIELD_DATA_DECENTRALIZED',
    UNSHIELD_DATA_CENTRALIZED: '$UNSHIELD_DATA_CENTRALIZED',
    DEV_TEST_TOGGLE_UTXOS: '$DEV_TEST_TOGGLE_UTXOS',
    UTXOS_DATA: '$UTXOS_DATA',
    DEV_TEST_TOGGLE_HISTORY_DETAIL: '$DEV_TEST_TOGGLE_HISTORY_DETAIL',
    DEV_TEST_TOGGLE_LOG_APP: '$DEV_TEST_TOGGLE_LOG_APP',
};

const KEYS_TESTNET: IKeysTestnet = {
    PASSPHRASE_KEY: `${prefixNetwork}_$password`,
    DEFAULT_ACCOUNT_NAME: `${prefixNetwork}_$DEFAULT_ACCOUNT_NAME`,
    DISPLAYED_WIZARD: '$DISPLAYED_WIZARD',
    GAME_PLAYER_ID: `${prefixNetwork}_$GAME_PLAYER_ID`,
    USER: `${prefixNetwork}_USER_OBJECT_KEY`,
    LIST_DEVICE: `${prefixNetwork}_PRODUCT_LIST_KEY`,
    LIST_TOKEN: `${prefixNetwork}_LIST_TOKEN`,
    USER_UNFOLLOWING_TOKEN_ID_LIST: `${prefixNetwork}_$USER_UNFOLLOWING_TOKEN_ID_LIST`,
    DEX: `${prefixNetwork}_DEX`,
    UNISWAP_HISTORY: `${prefixNetwork}_UNISWAP_HISTORY`,
    DEX_HISTORY: `${prefixNetwork}_$DEX_HISTORY`,
    SEEN_DEPOSIT_GUIDE: `${prefixNetwork}_$SEEN_DEPOSIT_GUIDE`,
    PIN: `${prefixNetwork}_$PIN`,
    IS_CHECK_FOLLOWED_TOKEN: `${prefixNetwork}_$IS_CHECK_FOLLOWED_TOKEN`,
    IS_BACKEDUP_ACCOUNT: `${prefixNetwork}_$IS_BACKEDUP_ACCOUNT`,
    REDUX_STATE_RECEIVERS_IN_NETWORK: `${prefixNetwork}_$REDUX_STATE_RECEIVERS_IN_NETWORK`,
    REDUX_STATE_RECEIVERS_OUT_NETWORK: `${prefixNetwork}_$REDUX_STATE_RECEIVERS_OUT_NETWORK`,
    WITHDRAWAL_DATA: `${prefixNetwork}_$WITHDRAWAL_DATA`,
    SUBSCRIBE_TOPIC_KEY: 'all-staging',
    BACKUP_STAKE_KEY: `${prefixNetwork}_$BACKUP_STAKE_KEY`,
    SCREEN_STAKE_GUIDE: `${prefixNetwork}_$SCREEN_STAKE_GUIDE`,
    PROVIDE_TXS: `${prefixNetwork}_$PROVIDE_TXS`,
    SHOW_WIZARD: `${prefixNetwork}_$SHOW_WIZARD`,
    IS_FOLLOW_DEFAULT_PTOKENS: `${prefixNetwork}_$IS_FOLLOW_DEFAULT_PTOKENS`,
    DETECT_NETWORK_NAME: `${prefixNetwork}_$DETECT_NETWORK_NAME`,
    DEV_TEST_MODE_CENTRALIZED: `${prefixNetwork}_$DEV_TEST_MODE_CENTRALIZED`,
    DEV_TEST_MODE_DECENTRALIZED: `${prefixNetwork}_$DEV_TEST_MODE_DECENTRALIZED`,
    UNSHIELD_DATA_DECENTRALIZED: `${prefixNetwork}_$UNSHIELD_DATA_DECENTRALIZED`,
    UNSHIELD_DATA_CENTRALIZED: `${prefixNetwork}_$UNSHIELD_DATA_CENTRALIZED`,
    DEV_TEST_TOGGLE_UTXOS: `${prefixNetwork}_$DEV_TEST_TOGGLE_UTXOS`,
    UTXOS_DATA: `${prefixNetwork}_$UTXOS_DATA`,
    DEV_TEST_TOGGLE_HISTORY_DETAIL: `${prefixNetwork}_DEV_TEST_TOGGLE_HISTORY_DETAIL`,
    DEV_TEST_TOGGLE_LOG_APP: `${prefixNetwork}_$DEV_TEST_TOGGLE_LOG_APP`,
};

export default isMainnet ? KEYS : KEYS_TESTNET;
