export const ACTION_CREATE_PASSWORD = `CREATE_PASSWORD`;
export const ACTION_CHANGE_PASSWORD = `CHANGE_PASSWORD`;
export const ACTION_LOGIN = `ACTION_LOGIN`;
export const ACTION_LOGOUT = `ACTION_LOGOUT`;
