export const EXTENSION_URL = chrome.extension.getURL('index.html#popup');
export const NOTIFICATION_HEIGHT = 610;
export const NOTIFICATION_WIDTH = 355;

// Message
export const REQUEST_CONNECT_ACCOUNT    
= 'REQUEST_CONNECT_ACCOUNT';

export const INCOGNITO_EXTENSION_SEND_DATA 
= 'INCOGNITO_EXTENSION_SEND_DATA';

// MESSAGE CONTENT LISTEN
export const CONTENT_LISTEN = {
    CONNECT_TO_ACCOUNT_SUCCESS: 'CONTENT_CONNECT_TO_ACCOUNT_SUCCESS',
    DISCONNECT_ACCOUNT: 'CONTENT_DISCONNECT_ACCOUNT',
    SEND_TX_FINISH: 'CONTENT_SEND_TX_FINISH',
    CANCEL_SEND_TX: 'CONTENT_CANCEL_SEND_TX',
};


// MESSAGE EXTENSION LISTEN
export const EXTENSION_LISTEN = {
    MOVE_TO_CONNECT_ACCOUNT: 'EXTENSION_MOVE_TO_CONNECT_ACCOUNT',
    MOVE_TO_SEND_TX: 'EXTENSION_MOVE_TO_SEND_TX',
};

// MESSAGE BACKGROUND LISTEN
export const BACKGROUND_LISTEN = {
    SELECTED_CONNECT_ACCOUNT: 'BACKGROUND_SELECTED_CONNECT_ACCOUNT',
    LOADED_FOLLOWED_BALANCE: 'BACKGROUND_LOADED_FOLLOWED_BALANCE',
    REQUEST_CONNECT_ACCOUNT: 'BACKGROUND_REQUEST_CONNECT_ACCOUNT',
    REQUEST_SEND_TX: 'BACKGROUND_REQUEST_SEND_TX',
    CHECK_CONNECT_ACCOUNT: 'BACKGROUND_CHECK_CONNECT_ACCOUNT',
    REQUEST_RELOAD_ACCOUNT: 'BACKGROUND_REQUEST_RELOAD_ACCOUNT',
    DISCONNECT_ACCOUNT: 'BACKGROUND_DISCONNECT_ACCOUNT',
    CHECK_IS_CONNECTED: 'BACKGROUND_CHECK_IS_CONNECTED',
    SEND_TX_FINISH: 'BACKGROUND_SEND_TX_FINISH',
    CLEAR_SEND_CURRENT_REQUEST: 'BACKGROUND_CLEAR_SEND_CURRENT_REQUEST',
    GET_PASS_WORD: 'BACKGROUND_GET_PASS_WORD',
    UPDATE_PASS_WORD: 'BACKGROUND_UPDATE_PASS_WORD',
    CHECK_WALLET_HAVE_CONNECTION: 'BACKGROUND_CHECK_WALLET_HAVE_CONNECTION',
    REMOVE_ACCOUNT: 'BACKGROUND_REMOVE_ACCOUNT',
};